name: Artifacts

on:
  create:
    tags:
      - v*

jobs:
  artifact-building:
    name: 'Build: ${{ matrix.config.name }} ${{ matrix.submodule_config.output }} '
    runs-on: ${{ matrix.config.os }}
    if: ${{ github.ref == 'refs/heads/releases' }}
    strategy:
      fail-fast: false
      matrix:
        submodule_config:
          - {
              dirname: 'Sairem-ces356',
              script_command: compile.sh,
              output: ces356
          }
          - {
              dirname: 'Sairem-ces362',
              script_command: compile.sh,
              output: ces362
          }
        config:
          - {
            name: 'bsp-build',
            os: ubuntu-latest,
            cxx: 'path/to/custom/armadeus/bsp'
          }
          - {
            name: 'desktop-build',
            os: ubuntu-latest,
            cxx: 'g++'
          }
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        token: ${{ secrets.PERMISSION_KEY }}
    - name: 'Create the ${{ matrix.submodule_config.bin }} dummy binaries'
      working-directory: ${{ github.workspace }}/${{ matrix.submodule_config.dirname }}
      run: |
        ./${{ matrix.submodule_config.script_command }}
        mkdir -p ${{ github.workspace }}/Artifacts/Update/
        mv ${{ matrix.submodule_config.output }} ${{ github.workspace }}/Artifacts/Update/
    - name: 'Upload the cached artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: 'releases'
        path: ${{ github.workspace }}/Artifacts/Update/

  artifacts-upload:
    name: 'Upload the artifacts'
    runs-on: ubuntu-latest
    needs: artifact-building
    steps:
    - name: 'Upload the artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: 'release'
        path: ${{ github.workspace }}/Artifacts/Update/
